core/urls.py
from django.urls import path, re_path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    AddCouponView,
    RequestRefundView,
    CatalogView,
    Get_Order
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    re_path('.?send-mail/', HomeView.send_mail, name='send-mail'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/<int:quantity>/', CheckoutView.add_to_cart, name='add-to-cart'),
    path('add-to-cart/<slug>/', CheckoutView.add_to_cart, name='add-to-cart-slug'),
    path('add-single-item-to-cart/<slug>/', OrderSummaryView.add_single_item_to_cart, name='add-single-item-to-cart'),
    path('order-summary/async-remove-from-cart/', OrderSummaryView.async_remove_from_cart, name='async-remove-from-cart'),
    path('order-summary/pay/<orderID>/<authorizationID>', OrderSummaryView.pay, name='pay-transaction'),
    path('order-summary/has-active-order/', OrderSummaryView.hasActiveOrder, name='has-active-order'),
    path('order-summary/resume', OrderSummaryView.resume, name='pay-resume'),
    path('remove-item-from-cart-summary/<slug>/', OrderSummaryView.remove_single_item_from_cart, name='remove-item-from-cart-summary')
]

core/models/Item.py
from django.shortcuts import reverse
from django.db import models

CATEGORY_CHOICES = (
    ('M', 'Mujer'),
    ('H', 'Hombre'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('M', 'maybe'),  # juguetes que pueden interesar
    ('B', 'bSeller')  # juguetes bestSeller cambiar apenas pueda
 )

class Item(models.Model):
    title = models.CharField(max_length=100, unique=True)
    price = models.IntegerField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    long_description = models.TextField(blank=True, null=True)
    image = models.ImageField()
    image2 = models.ImageField(blank=True, null=True)
    image3 = models.ImageField(blank=True, null=True)
    image4 = models.ImageField(blank=True, null=True)
    image5 = models.ImageField(blank=True, null=True)
    largeImage = models.ImageField(blank=True, null=True)
    footerImage = models.ImageField(blank = True, null = True)
    footerImage2 = models.ImageField(blank = True, null = True)
    footerImage3 = models.ImageField(blank = True, null = True)
    stockQuantity = models.IntegerField(default=1)
    sales = models.IntegerField(default=0)
    smart = models.BooleanField(default=False)



    def __str__(self):
        return self.title


    def get_smart(self):
        return self.smart


    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart-slug", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:async-remove-from-cart", kwargs={
            'slug': self.slug
        })

    def image_generator(self):
        pass

    def is_available(self, quantity):
        if(self.stockQuantity >= quantity):
            self.decreaseStock(quantity)
            return True
        return False

    # when byuing
    def decreaseStock(self, quantity):
        self.stockQuantity -= quantity
        self.save(update_fields=['stockQuantity'])
    
    def get_dollar_price(self):
        return f"${self.price}"


    #def increaseUnreserved(self, quantity):
     #   self.unreservedQuantity += quantity
     #   self.save(update_fields=['unreservedQuantity'])

core/models/Payment.py
from django.contrib.sessions.models import Session
from django.conf import settings
from django.db import models

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.CharField(max_length=40)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user

core/views/CatalogView.py
from django.views.generic import ListView
from ..models import Item

class CatalogView(ListView):
    queryset = Item.objects.filter(stockQuantity__gt=0) #equivalent to stockQuantity > 0
    paginate_by = 30
    template_name = "catalog.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['maybeObjects'] = filter(lambda x: x.label == 'M', Item.objects.all())
        return context

    def get(self, request, *args, **kwargs):
        self.checkSessions()
        return super().get(request, *args, **kwargs)
    
    def checkSessions(self):
        pass

core/views/CheckoutView.py
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.sessions.models import Session
from django.http.response import JsonResponse
from .PayPalClient import PayPalClient
from django.views.generic import View
from django.shortcuts import redirect
from django.contrib import messages
from django.utils import timezone
from ..forms import CheckoutForm
from ..models import OrderItem
from ..forms import CouponForm
from ..models import Address
from ..models import Order
from ..models import Item

class CheckoutView(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.session.session_key, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'couponform': CouponForm(),
                'order': order,
                'DISPLAY_COUPON_FORM': True
            }

            shipping_address_qs = Address.objects.filter(
                user=self.request.session.session_key,
                address_type='S',
                default=True
            )
            if shipping_address_qs.exists():
                context.update(
                    {'default_shipping_address': shipping_address_qs[0]})

            billing_address_qs = Address.objects.filter(
                user=self.request.session.session_key,
                address_type='B',
                default=True
            )
            if billing_address_qs.exists():
                context.update(
                    {'default_billing_address': billing_address_qs[0]})

            return render(self.request, "checkout.html", context)
        except ObjectDoesNotExist:
            messages.info(self.request, "You do not have an active order")
            return redirect("core:checkout")

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.session.session_key, ordered=False)
            if form.is_valid():

                use_default_shipping = form.cleaned_data.get(
                    'use_default_shipping')
                if use_default_shipping:
                    print("Using the defualt shipping address")
                    address_qs = Address.objects.filter(
                        user=self.request.session.session_key,
                        address_type='S',
                        default=True
                    )
                    if address_qs.exists():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()
                    else:
                        messages.info(
                            self.request, "No default shipping address available")
                        return redirect('core:checkout')
                else:
                    print("User is entering a new shipping address")
                    shipping_address1 = form.cleaned_data.get(
                        'shipping_address')
                    shipping_address2 = form.cleaned_data.get(
                        'shipping_address2')
                    shipping_country = form.cleaned_data.get(
                        'shipping_country')
                    shipping_zip = form.cleaned_data.get('shipping_zip')

                    if self.is_valid_form([shipping_address1, shipping_country, shipping_zip]):
                        shipping_address = Address(
                            user=self.request.session.session_key,
                            street_address=shipping_address1,
                            apartment_address=shipping_address2,
                            country=shipping_country,
                            zip=shipping_zip,
                            address_type='S'
                        )
                        shipping_address.save()

                        order.shipping_address = shipping_address
                        order.save()

                        set_default_shipping = form.cleaned_data.get(
                            'set_default_shipping')
                        if set_default_shipping:
                            shipping_address.default = True
                            shipping_address.save()

                    else:
                        messages.info(
                            self.request, "Please fill in the required shipping address fields")

                use_default_billing = form.cleaned_data.get(
                    'use_default_billing')
                same_billing_address = form.cleaned_data.get(
                    'same_billing_address')

                if same_billing_address:
                    billing_address = shipping_address
                    billing_address.pk = None
                    billing_address.save()
                    billing_address.address_type = 'B'
                    billing_address.save()
                    order.billing_address = billing_address
                    order.save()

                elif use_default_billing:
                    print("Using the defualt billing address")
                    address_qs = Address.objects.filter(
                        user=self.request.session.session_key,
                        address_type='B',
                        default=True
                    )
                    if address_qs.exists():
                        billing_address = address_qs[0]
                        order.billing_address = billing_address
                        order.save()
                    else:
                        messages.info(
                            self.request, "No default billing address available")
                        return redirect('core:checkout')
                else:
                    print("User is entering a new billing address")
                    billing_address1 = form.cleaned_data.get(
                        'billing_address')
                    billing_address2 = form.cleaned_data.get(
                        'billing_address2')
                    billing_country = form.cleaned_data.get(
                        'billing_country')
                    billing_zip = form.cleaned_data.get('billing_zip')

                    if self.is_valid_form([billing_address1, billing_country, billing_zip]):
                        billing_address = Address(
                            user=self.request.session.session_key,
                            street_address=billing_address1,
                            apartment_address=billing_address2,
                            country=billing_country,
                            zip=billing_zip,
                            address_type='B'
                        )
                        billing_address.save()

                        order.billing_address = billing_address
                        order.save()

                        set_default_billing = form.cleaned_data.get(
                            'set_default_billing')
                        if set_default_billing:
                            billing_address.default = True
                            billing_address.save()

                    else:
                        messages.info(
                            self.request, "Please fill in the required billing address fields")

                payment_option = form.cleaned_data.get('payment_option')

                if payment_option == 'S':
                    return redirect('core:payment', payment_option='stripe')
                elif payment_option == 'P':
                    return redirect('core:payment', payment_option='paypal')
                else:
                    messages.warning(
                        self.request, "Invalid payment option selected")
                    return redirect('core:checkout')
        except ObjectDoesNotExist:
            messages.warning(self.request, "Aun no tienes una orden activa")
            return redirect("core:order-summary")
    
    def add_to_cart(request, slug, quantity):
        item = get_object_or_404(Item, slug=slug)
        try:
            stock = item.stockQuantity
            if(quantity <= stock):
                if request.session.session_key == None:
                    request.session.create()
                    request.session.set_expiry(150)
                order_item, created = OrderItem.objects.get_or_create(
                    item=item,
                    user=request.session.session_key,
                    ordered=False
                )
                order_qs = Order.objects.filter(user=request.session.session_key, ordered=False)
                if order_qs.exists():
                    order = order_qs[0]
                    # check if the order item is in the order
                    if order.items.filter(item__slug=item.slug).exists():
                        order_item.quantity += quantity
                        order_item.save()
                        return redirect("core:order-summary")
                    else:
                        order_item.quantity = quantity
                        order_item.save()
                        order.items.add(order_item)
                        return redirect("core:order-summary")
                else:
                    order_item.quantity = quantity
                    ordered_date = timezone.now()
                    order = Order.objects.create(
                        user=request.session.session_key, ordered_date=ordered_date)
                    order_item.save()
                    order.items.add(order_item)
                    return redirect("core:order-summary")
            elif (item.stockQuantity == 0):
                messages.info(request, "Este producto se acaba de agotar")
                return redirect("core:product", slug=slug)
            else:

core/views/HomeView.py
from django.http.response import JsonResponse
from django.views.generic import ListView
from django.core.mail import EmailMessage
from ..models import Item

class HomeView(ListView):
    model = Item
    paginate_by = 10
    template_name = "home.html"

    def fudfd(self, item):
        if item.label == 'B':
            return True
        else:
            return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count'] = 0
        context['best_seller_c'] = filter(self.fudfd, Item.objects.all())
        context['maybeObjects'] = filter(lambda x: x.label == 'M', Item.objects.all())
        return context

    def send_mail(request):
        try:
            print("enters")
            if request.is_ajax() and request.method == "GET":
                mail = request.GET.get("mail")
                email = EmailMessage(
                'SashaShop contacto', HomeView.getMailMessage(), "sashacollectioncr@gmail.com", [mail])
                email.send()
                return JsonResponse({"scc": "true"}, status=200)
            else:
                return JsonResponse({"scc": "false"}, status=400)
        except:
            return JsonResponse({"scc": "false"}, status=400)
    
    def getMailMessage():
        message = f'''Hola!
Gracias por confiar en nosotros y ponerte en contacto.
¿Cómo podemos ayudarte?'''
        return message

core/views/RequestRefundView.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.shortcuts import redirect
from django.contrib import messages
from ..forms import RefundForm
from ..models import Order
from ..models import Refund

class RequestRefundView(View):
    def get(self, *args, **kwargs):
        form = RefundForm()
        context = {
            'form': form
        }
        return render(self.request, "request_refund.html", context)

    def post(self, *args, **kwargs):
        form = RefundForm(self.request.POST)
        if form.is_valid():
            ref_code = form.cleaned_data.get('ref_code')
            message = form.cleaned_data.get('message')
            email = form.cleaned_data.get('email')
            # edit the order
            try:
                order = Order.objects.get(ref_code=ref_code)
                order.refund_requested = True
                order.save()

                # store the refund
                refund = Refund()
                refund.order = order
                refund.reason = message
                refund.email = email
                refund.save()

                messages.info(self.request, "Your request was received.")
                return redirect("core:request-refund")

            except ObjectDoesNotExist:
                messages.info(self.request, "This order does not exist.")
                return redirect("core:request-refund")

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/footer.html
{% load static %}
<script type="text/javascript" src="{% static 'js/footer/footer.js' %}"></script>
<footer style="background-color: #2f4555;">
  <div class="">
    <div class="container">

      <div class="row">

        <div class="col-md-6 col-lg-3 col-12">
          <img class="logomf" src="{% static 'img/logoblanco.png' %}">
          <h5 class="Contactomf">sashashopcr@gmail.com</h5>
        </div>


        <div class="col-md-2 col-12 menufl">
          <nav>
            <ul>
              <li class="menufooter"><a class="linkmenufooter" href="/">Inicio</a></li>
              <li class="menufooter"><a class="linkmenufooter" href="{% url 'core:catalog' %}">Juguetes</a></li>
              <li class="menufooter"><a class="linkmenufooter" href="/#favoritomenu">Favoritos</a></li>
              <li class="menufooter"><a class="linkmenufooter" href="/#seleccionamos">Seleccionamos</a>
              </li>
            </ul>
          </nav>
        </div>

        <div class="col-md-6 col-lg-3 col-12 menufl2">
          <nav>
            <ul>
              <a class="linkmenufooter" href="{% url 'core:catalog' %}">
                <li onclick="SaveCategory('category', 'men')" class="menufooter">For Him</li>
              </a>
              <a class="linkmenufooter" href="{% url 'core:catalog' %}">
                <li onclick="SaveCategory('category', 'women')" class="menufooter">For Her</li>
              </a>
              <a class="linkmenufooter" href="{% url 'core:catalog' %}">
                <li onclick="SaveCategory('category', 'smart')" class="menufooter">Smart Toys</li>
              </a>
            </ul>
          </nav>
          <a target="_blank" rel="noopener" href="https://www.instagram.com/sashashop.cr/" style="cursor: pointer">
            <img class="instaimf" src="{% static 'img/instagram.png' %}">
          </a>
        </div>

        <div class="col-md-6 col-lg-4 col-12 menufl3">
          <form class="formfooter">
            <div class="form-row">
              <small id="emailHelp" class="col-12 form-text text-muted mensajf">Mandanos tu correo y
                te contactamos</small>
              <div class="col-12 form-group">
                <input type="text" id="mailfield" class="form-control textinfc" placeholder="E-mail">
              </div>
            </div>
          </form>
          <button type="button" onclick="sendMail()" class="btn btn-outline-light">Enviar</button>
        </div>

      </div>
    </div>

  </div>


  <div class="">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-1"></div>
        <div class="col-md-4 col-10">
          <h6 class="derechosr" style="color: white">&copy; Derechos Reservados</h6>
        </div>
        <div class="col-md-4 col-1"></div>
      </div>
    </div>
  </div>

</footer>

<div class="modal fade" id="MailSended" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-md" style="background-color: #d1a2a3">
            <div class="container">
                <div class="row">
                    <div class="col-9"></div>
                    <div class="col-3">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-12"><h3 class="mensage-carrito mt-4">En breve te llegará un correo de parte de Sasha Shop, ¡Revísalo!</h3></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="MailNotSended" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-md" style="background-color: #d1a2a3">
            <div class="container">
                <div class="row">
                    <div class="col-9"></div>
                    <div class="col-3">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-12"><h3 class="mensage-carrito mt-4">Ocurrió un error al enviar el mensaje, ponte en contacto con nosotros a sashashopcr@gmail.com</h3></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

templates/product2.html
{% extends "base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}


  
<!--<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
 Bootstrap tooltips
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript 
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
Initializations 
<script type="text/javascript">
  // Animations initialization
  new WOW().init();-->

</script>

<script>
    function async_remove_from_cart_funtion(slug) {
        $.ajax({
            type: 'GET',
            url: "{% url 'core:async-remove-from-cart' %}",
            data: {"slug": slug},
            success: function (response) {
                // if not valid user, alert the user
                if(response["scc"]){
                    RowToDelete = document.getElementById(slug + "CartRow");
                    padre = RowToDelete.parentNode;
		            padre.removeChild(RowToDelete);
                    var oldQ = parseInt(document.getElementById("CartItemCount").innerHTML.trim());
                    document.getElementById("CartItemCount").innerHTML = " " + (oldQ - 1) + " ";
                }
            },
            error: function (response) {
                console.log(response)
            }
        })
    }
    function remove_single_item_from_cart_funtion(slug) {
        $.ajax({
            type: 'GET',
            url: "{% url 'core:remove-single-item-from-cart' %}",
            data: {"slug": slug},
            success: function (response) {
                // if not valid user, alert the user
                if(response["scc"]){
                    var oldQ = parseInt(document.getElementById(slug).innerHTML.trim());
                    document.getElementById(slug).innerHTML = " " + (oldQ - 1) + " ";
                }
            },
            error: function (response) {
                console.log(response)
            }
        })
    }
    function add_single_item_to_cart_funtion(slug) {
        $.ajax({
            type: 'GET',
            url: "{% url 'core:add-single-item-to-cart' %}",
            data: {"slug": slug},
            success: function (response) {
                // if not valid user, alert the user
                if(response["scc"]){
                    var oldQ = parseInt(document.getElementById(slug).innerHTML.trim());
                    document.getElementById(slug).innerHTML = " " + (oldQ + 1) + " ";
                }
            },
            error: function (response) {
                console.log(response)
            }
        })
    }
</script>